#!/bin/sh
set -eu

staged_files=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$staged_files" ]; then
	exit 0
fi

bunx biome check --write --staged
git diff --cached --name-only --diff-filter=ACMR -z | xargs -0 git add --
