#!/bin/sh
set -eu

case "$1" in
  "$PWD"/apps/web/*)
    exec "$PWD/apps/web/node_modules/.bin/biome" format --config-path "$PWD/apps/web/biome.json" --stdin-file-path "$1"
    ;;
esac

exec "$PWD/node_modules/.bin/biome" format --stdin-file-path "$1"
